### ISSUE TITLE
cannot match/peek '\' charactor (generated code missing escape)

### ISSUE THREAD

**Issue by terrywh** [nodejs/llparse#23]
i'm tring to use llparse to create a parser for TOML ([lltoml](http://github.com/terrywh/lltoml)) and encounters a problem when match trailing "\\" to concat long string;

i cannot match/peek '\\' charactor (generated code missing escape which cause compile problem):
generate code:
```
case '\': 
```
maybe change to `case 92:` / `case '\\':` instead ? @indutny

**Comment by indutny** [comment]
Sorry about that! Should be fixed in 6.02, please give it a try!

**Comment by terrywh** [comment]
confirm fixed. thanks~

**Comment by indutny** [comment]
Awesome! Thank you!
