### ISSUE TITLE
Support conflicting select/match

### ISSUE THREAD

**Issue by indutny** [nodejs/llparse#28]
It should be possible to generate code for:

```
node
  .match('undef', ...)
  .match('undefined', ...);
```

The compiler could turn it into a tree of `match`+`peek`.

**Comment by drom** [comment]
Yes, that would be very useful.

**Comment by knopp** [comment]
This would be very helpful indeed. We're currently using modified http_parse and I'd like to switch to  llhttp. We need to add RTSP support, which brings additional methods, one of which is `GET_PARAMETER`, which conflicts with `GET`. Our workaround right now is to append space to METHOD_MAP keys and then skip immediately to `req_spaces_before_url` (ignoring `req_first_space_before_url`). 

It's not the end of the world, but having this working out of box would be much nicer :)

**Comment by knopp** [comment]
Just in case it helps someone, this [commit](https://github.com/knopp/llhttp/commit/0192e9a134e693f71fab9b8796709703af009889) in my fork adds RSTP support to llhttp. While having to append space to remove conflict is less than ideal, it's still lot cleaner than adding RTSP to original http-parser :)

**Comment by indutny** [comment]
I've just published a new version of llparse that supports this. Could you give it a try?

**Comment by knopp** [comment]
Thanks! I gave it a go, unfortunately it doesn't seem to work for me. You can see my [branch](https://github.com/knopp/llhttp/tree/conflicting_select) here. It builds the parser but tests fail.

I might be doing something wrong, but I have both `GET` and `GET_PARAMETER` methods defined, all tests fail with `method=0` instead of expected `method=1`. If I remove `GET_PARAMETER` method from the list tests pass.

**Comment by indutny** [comment]
Gosh, values... Sorry!

**Comment by indutny** [comment]
Alright. Should be really fixed now. Please give it another try!

**Comment by knopp** [comment]
Seems to be working! Tests passed and I did some testing with built parser which also works. Thanks!

**Comment by indutny** [comment]
Yay! Glad to help!
