### ISSUE TITLE
streaming parser

### ISSUE THREAD

**Issue by drom** [nodejs/llparse#29]
I am building VCD (Value Change Dump) parser using llparse. These types of files can grow very big >1GB. Is it possible to implement streaming parser using llparse? The idea is to feed it chunk by chunk and keep state between chunks.

**Comment by indutny** [comment]
Totally! The parser will save the state and wait for more data. Just call `_execute()` for each successive chunk.

**Comment by drom** [comment]
I struggle to make it work. Since the first chunk `_execute()` was incomplete, it produced an error.
Second `_execute()` did not even run for some reason?

Here is the test: https://github.com/wavedrom/vcd/blob/master/test/basic.js#L46
