### ISSUE TITLE
streaming execute

### ISSUE THREAD

**Issue by drom** [nodejs/llparse#30]
I am trying to make streaming execute to work as it was discussed in #29 .

I struggle to make it work. Since the first chunk `_execute()` was incomplete, it produced an error.
Second `_execute()` did not even run for some reason?

Here is the test: https://github.com/wavedrom/vcd/blob/master/test/basic.js#L49

**Comment by drom** [comment]
I noticed that I can clean `status->error` before running execute and it helps.

**Comment by indutny** [comment]
I'd love to take a look. How can I reproduce this?

**Comment by indutny** [comment]
FWIW, tests appear to pass in your repo when I run it locally.

**Comment by drom** [comment]
Sorry for a false alarm, it was my bug. It fixed it somehow in the process.
