### ISSUE TITLE
Rename primary branch to main

### ISSUE THREAD

**Issue by mhdawson** [nodejs/llparse#45]
We are going through all of the node.js repositories to rename the primary branch to main. Please see nodejs/node#33864 for more context.

I also don't see any references to master other than URL links which the auto redirect should handle so I don't think there should be issues with the rename.

Please let me know if there are any concerns otherwise I'll look to do the rename Friday May 4th.

**Comment by mhdawson** [comment]
@indutny any concern over the rename?

**Comment by indutny** [comment]
No concern, but CI. Thanks!

**Comment by mhdawson** [comment]
Thanks, renamed.
