### ISSUE TITLE
llparse.org is down

### ISSUE THREAD

**Issue by isiahmeadows** [nodejs/llparse#48]
https://llparse.org/ currently returns a 404.

**Comment by indutny** [comment]
cc @nodejs/tsc I don't know if this is configuration issue in this repo or in my dns config...

**Comment by targos** [comment]
According to GitHub, it's a DNS issue:

![image](https://user-images.githubusercontent.com/2352663/151122450-7256e390-d545-4972-93ce-0b2c7879ff52.png)

**Comment by indutny** [comment]
Thanks! Changed the config. Hopefully it will help.

**Comment by isiahmeadows** [comment]
@indutny Still showing 404. Been 5 days, so I'm pretty sure DNS changes should have already propagated by now.

**Comment by indutny** [comment]
Weird! This is how DNS records look like on my end:
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/238531/151861272-dc852efc-616d-4474-80cb-d553a094f491.png">

Note that I couldn't do CNAME for `llparse.org` (dnsimple doesn't let me), so I used ALIAS. Strangely the same ALIAS appears to be working for llhttp.org

**Comment by targos** [comment]
I tried to force-push main (without changes), but nothing happened.
Then I merged https://github.com/nodejs/llparse/pull/47. Now the site is back up.

**Comment by isiahmeadows** [comment]
Okay, can confirm it's up now.

**Comment by indutny** [comment]
Awesome. Thanks y’all!
